GET http://localhost:3000/users

###

GET http://localhost:3000/fetch-joke
Authorization: <Enter new generated TOKEN HERE>

###

POST  http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "test4@gmail.com",
    "password": "test123",
    "firstName": "Test4",
    "lastName": "Test4"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "test4@gmail.com",
    "password": "test123"
}